# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site settings
title: Ariz Mua Jiani San
email: your-email@example.com  # Consider using a GitHub-provided no-reply email
description: >-
  Personal blog and portfolio of Ariz Mua Jiani San. Sharing thoughts, projects, and experiences.

# GitHub Pages settings
baseurl: "" # Leave this empty if using a custom domain or username.github.io
url: "https://arizmuajianisan.github.io" # Your GitHub Pages URL

# Social media usernames
twitter_username: "" # Your Twitter username (without @)
github_username:  arizmuajianisan # Your GitHub username

# Build settings
# Theme settings
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag  # For better SEO

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .gitignore
  - .github/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - .DS_Store
